fix build_args with non `--test` argument
[INFO ]    Executing test (testAlu)
  File "/tmp/.tmpI7QCnb/runner.py", line 13
    build_args=,
    ^^^^^^^^^^^
SyntaxError: expected argument value expression

forgot to add `[]` to build_args